### PR TITLE
Added Doit Archives

### PR DESCRIPTION
**Pull request by ragnar76**

### CODE REVIEW

**Comment by ggnkua** [comment]
Hi,

I added the doit archives as a submodule a few months ago (from https://github.com/doitarchive/doit_st). Is it not working for you? If it does, is your copy different than that repository?

I'm a bit confused :)

**Comment by ragnar76** [comment]
Oh, i created that repo a long time ago (and forgot this). It is the same i
have addad now

ggnkua <notifications@github.com> schrieb am Di., 5. Juni 2018, 16:58:

**Comment by ggnkua** [comment]
Ok, I'll won't merge the request then. Thanks a lot for taking the time to do this in any case!

**Comment by ragnar76** [comment]
Maybe i will add "my" bootstrapped Version Kater butbits messy as hell and needs some rework

**Pull request closed without merging**
